kind: pipeline
type: docker
name: default

steps:
- name: build-linux
  image: python:3.8
  commands:
  - pip install --upgrade pip
  - pip install --upgrade cx_Freeze
  - pip install -r requirements.txt
  - python setup.py build

trigger:
  event:
    include:
    - push
    - custom
